version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hostIsUp-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1k3bbbcqzdhxs"
s3_prefix = "hostIsUp-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
